# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Umshini Server Integration

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  DEBUG: "TRUE"
  SECRET_KEY: BANANA
  SENDGRID_API_KEY: BANANA
  OPENAI_API_KEY: ${{ secrets.openai_api_key }}
  OPENAI_API_TYPE: azure
  OPENAI_API_BASE: https://testy-test.openai.azure.com/
  OPENAI_API_VERSION: 2023-06-01-preview
  DEPLOYMENT_NAME: chatgpt-16k

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: ["connect_four_v3", "texas_holdem_no_limit_v6"]
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Umshini-Server using private key
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
        git clone git@github.com:Umshini/Umshini-Server.git
        cd Umshini-Server && pip install -e . && cd ..
    - name: Install Umshini-client dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[all,testing]' --upgrade
    - name: Run servers
      run: |
        cd Umshini-Server
        python -m umshini_server.server.create_test_db --test
        python -m umshini_server.server.run_admin &
        python -m umshini_server.server.standalone_game_server &
        python -m umshini_server.server.tournament_matchmaker -e ${{ matrix.env_name }} -p 4 &
        cd ..
        pytest -v tests/test_umshini_client.py --env_name ${{ matrix.env_name }} --cache-clear
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-integration-${{ matrix.env_name }}
        path: .coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        flags: integration
