# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
---
name: Windows Tests

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  windows-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -e '.[all,testing]'
      - name: Source distribution test
        run: |
          python -m pip install --upgrade build
          python -m build --sdist
          pip install dist/umshini-$(python -c "import umshini; print(umshini.__version__)").tar.gz
      - name: Release Test
        run: |
          pytest -v --cov=umshini --cov-report term --cache-clear
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-windows-test-${{ matrix.python-version }}
          path: .coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: windows-test
